### ISSUE TITLE
requestID being used in place of subscriptionID

### ISSUE THREAD

**Issue by SquareMike** [killbill/killbill-cybersource-plugin#14]
I see here (https://github.com/killbill/killbill-cybersource-plugin/blob/master/lib/cybersource/ext/active_merchant/active_merchant.rb#L137) that we are packing the requestID into the authorization string, delimited by semicolons.  However, here (https://github.com/activemerchant/active_merchant/blob/master/lib/active_merchant/billing/gateways/cyber_source.rb#L605) we unpack that string to get the subscriptionID.

When doing a vanilla recurring payment test with Cybersource I am seeing that the requestID is being sent to Cybersource in the recurringSubscriptionInfo/subscriptionID field.  Naturally Cybersource is replying with a 102;INVALIDDATA error as the requestID can not be used as a subscriptionID.  If I manually put the subscriptionID into the XML request then the request succeeds.  I do see many places in activemerchant where the requestID is unpacked from the ;-delimited string and used properly.

Is this a bug, a case of trying to get the subscriptionID from the wrong place?  Seems odd that this bug has gone un-noticed for so long which makes me wonder if I am just using the software wrong.

**Comment by pierre** [comment]
A few thoughts:

* Make sure to always look at the right ActiveMerchant version, as locked by the plugin (see [Gemfile.lock#L34](https://github.com/killbill/killbill-cybersource-plugin/blob/master/Gemfile.lock#L34). Unfortunately, the plugin had to extend the upstream ActiveMerchant implementation and we weren't able to contribute back these patches (meaning we effectively fork it).
* Am I correct that you are trying to have CyberSource manage recurring payments? It probably has never been tested because it's the role of Kill Bill to trigger these payments (e.g. after an invoice is generated)! 😸 Do you have a use-case where you must delegate recurring payments to CyberSource?
* Happy holidays! 🎅 🎄

**Comment by SquareMike** [comment]
Good point about the locked versions but the line I outlined is in the version pulled into killbill-cybersource.  My Gemfile.lock file says activemerchant ~1.48.0 and 1.48.0.  That matches what is currently in killbill-cybersource 5.0.1.

I am not having Cybersource manage the recurring payments, the plugin is managing it like you said it should.  I am doing POST /1.0/kb/accounts/<aId>/paymentMethods without skip_gw which goes to Cybersource with a cc (or Apple Pay encrypted token in my case) and gets back a subscriptionId.  I then call POST /1.0/kb/subscriptions on the same account which goes to Cybersource with a subscriptionId (but the plugin is actually putting the requestID into the subscriptionId field).  I am using the system differently than it was designed to be used?

Happy Holidays to you too Pierre.

**Comment by pierre** [comment]
> I am using the system differently than it was designed to be used?

No, the flow sounds great. I'm just confused about the requestId vs subscriptionId issue (see also https://github.com/activemerchant/active_merchant/blob/master/lib/active_merchant/billing/gateways/cyber_source.rb#L693).

Could you share your Kill Bill requests (POST payload) and XML back/forth from CyberSource? Maybe that will help debug the problem.

Payments with a token are definitively supported (see https://github.com/killbill/killbill-cybersource-plugin/blob/master/spec/cybersource/base_plugin_spec.rb#L356-L359).

**Comment by SquareMike** [comment]
To simplify, I have backed out our customized containers and ran the test using the provided killbill testing instructions:
`docker run -tid            --name killbilltest            -p 8080:8080            --link mysql:mysql            -e KILLBILL_PLUGIN_CYBERSOURCE=1            -e KILLBILL_CONFIG_DAO_URL=jdbc:mysql://mysql:3306/killbill            -e KILLBILL_CONFIG_DAO_USER=root            -e KILLBILL_CONFIG_DAO_PASSWORD=mysecretpassword            -e KILLBILL_CONFIG_OSGI_DAO_URL=jdbc:mysql://mysql:3306/killbill            -e KILLBILL_CONFIG_OSGI_DAO_USER=root            -e KILLBILL_CONFIG_OSGI_DAO_PASSWORD=mysecretpassword            killbill/killbill:0.18.1`

POST http://127.0.0.1:8080/1.0/kb/accounts/0e8bcdf6-36c6-4218-ab10-dea993b08f31/paymentMethods?isDefault=true
`{
       "pluginName": "killbill-cybersource",
       "pluginInfo": {
         "properties": [
           {
             "key": "ccFirstName",
             "value": "John"
           },
           {
             "key": "ccLastName",
             "value": "Doe"
           },
           {
             "key": "address1",
             "value": "5th Street"
           },
           {
             "key": "city",
             "value": "San Francisco"
           },
           {
             "key": "zip",
             "value": "94111"
           },
           {
             "key": "state",
             "value": "CA"
           },
           {
             "key": "country",
             "value": "USA"
           },
           {
            "key": "email",
             "value": "mcassano@gmail.com"
           },
           {
             "key": "ccExpirationMonth",
             "value": 12
           },
           {
             "key": "ccExpirationYear",
             "value": 2017
           },
           {
             "key": "ccNumber",
             "value": "4111111111111111"
           }
         ]
       }
     }
     `

Resulting XML to Cybersource from killbill logs:
`<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<s:Envelope xmlns:s=\"http://schemas.xmlsoap.org/soap/envelope/\">\n  <s:Header>\n    <wsse:Security s:mustUnderstand=\"1\" xmlns:wsse=\"http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd\">\n      <wsse:UsernameToken>\n        <wsse:Username>**********</wsse:Username>\n        <wsse:Password Type=\"http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-username-token-profile-1.0#PasswordText\">****</wsse:Password>\n      </wsse:UsernameToken>\n    </wsse:Security>\n  </s:Header>\n  <s:Body xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\n    <requestMessage xmlns=\"urn:schemas-cybersource-com:transaction-data-1.109\">\n      <merchantID>squaretrad</merchantID>\n      <merchantReferenceCode>ea38befb-46c2-45a6-b4fd-84f8199cf49e</merchantReferenceCode>\n      <clientLibrary>Kill Bill</clientLibrary>\n      <clientLibraryVersion>5.0.1</clientLibraryVersion>\n      <clientEnvironment>java</clientEnvironment>\n<billTo>\n  <firstName>****</firstName>\n  <lastName>***</lastName>\n  <street1>5th Street</street1>\n  <city>San Francisco</city>\n  <state>CA</state>\n  <postalCode>94111</postalCode>\n  <country>USA</country>\n  <email>******************</email>\n</billTo>\n<purchaseTotals>\n  <currency>USD</currency>\n  <grandTotalAmount>0.00</grandTotalAmount>\n</purchaseTotals>\n<card>\n  <accountNumber>****************</accountNumber>\n  <expirationMonth>12</expirationMonth>\n  <expirationYear>2017</expirationYear>\n  <cardType>001</cardType>\n</card>\n<subscription>\n  <paymentMethod>credit card</paymentMethod>\n</subscription>\n<recurringSubscriptionInfo>\n  <amount>0.00</amount>\n  <frequency>on-demand</frequency>\n  <approvalRequired>false</approvalRequired>\n</recurringSubscriptionInfo>\n<paySubscriptionCreateService run=\"true\"/>\n<businessRules>\n</businessRules>\n    </requestMessage>\n  </s:Body>\n</s:Envelope>\n`

And the response from Cybersource:
`<?xml version=\"1.0\" encoding=\"utf-8\"?><soap:Envelope xmlns:soap=\"http://schemas.xmlsoap.org/soap/envelope/\">\n<soap:Header>\n<wsse:Security xmlns:wsse=\"http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd\"><wsu:Timestamp xmlns:wsu=\"http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd\" wsu:Id=\"Timestamp-2053696978\"><wsu:Created>2016-12-25T14:08:20.963Z</wsu:Created></wsu:Timestamp></wsse:Security></soap:Header><soap:Body><c:replyMessage xmlns:c=\"urn:schemas-cybersource-com:transaction-data-1.109\"><c:merchantReferenceCode>ea38befb-46c2-45a6-b4fd-84f8199cf49e</c:merchantReferenceCode><c:requestID>4826749006876015001014</c:requestID><c:decision>ACCEPT</c:decision><c:reasonCode>100</c:reasonCode><c:requestToken>Ahj/7wSTBaiZOIqeWv22KhDdm4aMmTNwlwzn0FRAKXDOfQVFpABjYhk0kUqyALxZWBOTBaiZOIqeWv22AAAA5Qex</c:requestToken><c:purchaseTotals><c:currency>USD</c:currency></c:purchaseTotals><c:ccAuthReply><c:reasonCode>100</c:reasonCode><c:amount>0.00</c:amount><c:authorizationCode>831000</c:authorizationCode><c:avsCode>Y</c:avsCode><c:avsCodeRaw>Y</c:avsCodeRaw><c:authorizedDateTime>2016-12-25T14:08:20Z</c:authorizedDateTime><c:processorResponse>000</c:processorResponse><c:paymentNetworkTransactionID>558196000003814</c:paymentNetworkTransactionID><c:cardCategory>A</c:cardCategory></c:ccAuthReply><c:afsReply><c:reasonCode>100</c:reasonCode><c:afsResult>1</c:afsResult><c:hostSeverity>1</c:hostSeverity><c:consumerLocalTime>06:08:20</c:consumerLocalTime><c:afsFactorCode>T^U</c:afsFactorCode><c:addressInfoCode>UNV-ADDR</c:addressInfoCode><c:internetInfoCode>FREE-EM</c:internetInfoCode><c:suspiciousInfoCode>RISK-TB</c:suspiciousInfoCode><c:scoreModelUsed>default</c:scoreModelUsed><c:binCountry>US</c:binCountry><c:cardScheme>VISA CREDIT</c:cardScheme><c:cardIssuer>JPMORGAN CHASE BANK, N.A.</c:cardIssuer></c:afsReply><c:paySubscriptionCreateReply><c:reasonCode>100</c:reasonCode><c:subscriptionID>013679******1111</c:subscriptionID></c:paySubscriptionCreateReply><c:decisionReply><c:activeProfileReply/></c:decisionReply></c:replyMessage></soap:Body></soap:Envelope>`

Note the subscriptionID starts with 0136, and the requestID starts with 4826.

POST http://127.0.0.1:8080/1.0/kb/subscriptions 
`{"accountId":"0e8bcdf6-36c6-4218-ab10-dea993b08f31","externalKey":"{{$guid}}","planName":"RD-SP1499RR10A"}`

Resulting XML to Cybersource from killbill logs:
`<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<s:Envelope xmlns:s=\"http://schemas.xmlsoap.org/soap/envelope/\">\n  <s:Header>\n    <wsse:Security s:mustUnderstand=\"1\" xmlns:wsse=\"http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd\">\n      <wsse:UsernameToken>\n        <wsse:Username>**********</wsse:Username>\n        <wsse:Password Type=\"http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-username-token-profile-1.0#PasswordText\">****</wsse:Password>\n      </wsse:UsernameToken>\n    </wsse:Security>\n  </s:Header>\n  <s:Body xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\n    <requestMessage xmlns=\"urn:schemas-cybersource-com:transaction-data-1.109\">\n      <merchantID>squaretrad</merchantID>\n      <merchantReferenceCode>c601d466-4b47-4eba-b24d-ae1cdbd8a063</merchantReferenceCode>\n      <clientLibrary>Kill Bill</clientLibrary>\n      <clientLibraryVersion>5.0.1</clientLibraryVersion>\n      <clientEnvironment>java</clientEnvironment>\n<purchaseTotals>\n  <currency>USD</currency>\n  <grandTotalAmount>7.99</grandTotalAmount>\n</purchaseTotals>\n<recurringSubscriptionInfo>\n  <subscriptionID>4826749006876015001014</subscriptionID>\n  <approvalRequired>false</approvalRequired>\n</recurringSubscriptionInfo>\n<ccAuthService run=\"true\">\n</ccAuthService>\n<ccCaptureService run=\"true\"/>\n<businessRules>\n</businessRules>\n    </requestMessage>\n  </s:Body>\n</s:Envelope>\n`

See that the subscriptionID is 4826 not 0136 and Cybersource responded with REJECT;102;INVALIDDATA.  And if I put the 0136 in manually Cybersource responds ACCEPT;100.

**Comment by pierre** [comment]
Formatted version:

```
<?xml version="1.0" encoding="UTF-8"?>
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">
  <s:Header>
    <wsse:Security xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" s:mustUnderstand="1">
      <wsse:UsernameToken>
        <wsse:Username>**********</wsse:Username>
        <wsse:Password Type="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-username-token-profile-1.0#PasswordText">****</wsse:Password>
      </wsse:UsernameToken>
    </wsse:Security>
  </s:Header>
  <s:Body xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <requestMessage xmlns="urn:schemas-cybersource-com:transaction-data-1.109">
      <merchantID>squaretrad</merchantID>
      <merchantReferenceCode>ea38befb-46c2-45a6-b4fd-84f8199cf49e</merchantReferenceCode>
      <clientLibrary>Kill Bill</clientLibrary>
      <clientLibraryVersion>5.0.1</clientLibraryVersion>
      <clientEnvironment>java</clientEnvironment>
      <billTo>
        <firstName>****</firstName>
        <lastName>***</lastName>
        <street1>5th Street</street1>
        <city>San Francisco</city>
        <state>CA</state>
        <postalCode>94111</postalCode>
        <country>USA</country>
        <email>******************</email>
      </billTo>
      <purchaseTotals>
        <currency>USD</currency>
        <grandTotalAmount>0.00</grandTotalAmount>
      </purchaseTotals>
      <card>
        <accountNumber>****************</accountNumber>
        <expirationMonth>12</expirationMonth>
        <expirationYear>2017</expirationYear>
        <cardType>001</cardType>
      </card>
      <subscription>
        <paymentMethod>credit card</paymentMethod>
      </subscription>
      <recurringSubscriptionInfo>
        <amount>0.00</amount>
        <frequency>on-demand</frequency>
        <approvalRequired>false</approvalRequired>
      </recurringSubscriptionInfo>
      <paySubscriptionCreateService run="true"/>
      <businessRules></businessRules>
    </requestMessage>
  </s:Body>
</s:Envelope>



<?xml version="1.0" encoding="utf-8"?>
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
  <soap:Header>
    <wsse:Security xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd">
      <wsu:Timestamp xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" wsu:Id="Timestamp-2053696978">
        <wsu:Created>2016-12-25T14:08:20.963Z</wsu:Created>
      </wsu:Timestamp>
    </wsse:Security>
  </soap:Header>
  <soap:Body>
    <c:replyMessage xmlns:c="urn:schemas-cybersource-com:transaction-data-1.109">
      <c:merchantReferenceCode>ea38befb-46c2-45a6-b4fd-84f8199cf49e</c:merchantReferenceCode>
      <c:requestID>4826749006876015001014</c:requestID>
      <c:decision>ACCEPT</c:decision>
      <c:reasonCode>100</c:reasonCode>
      <c:requestToken>Ahj/7wSTBaiZOIqeWv22KhDdm4aMmTNwlwzn0FRAKXDOfQVFpABjYhk0kUqyALxZWBOTBaiZOIqeWv22AAAA5Qex</c:requestToken>
      <c:purchaseTotals>
        <c:currency>USD</c:currency>
      </c:purchaseTotals>
      <c:ccAuthReply>
        <c:reasonCode>100</c:reasonCode>
        <c:amount>0.00</c:amount>
        <c:authorizationCode>831000</c:authorizationCode>
        <c:avsCode>Y</c:avsCode>
        <c:avsCodeRaw>Y</c:avsCodeRaw>
        <c:authorizedDateTime>2016-12-25T14:08:20Z</c:authorizedDateTime>
        <c:processorResponse>000</c:processorResponse>
        <c:paymentNetworkTransactionID>558196000003814</c:paymentNetworkTransactionID>
        <c:cardCategory>A</c:cardCategory>
      </c:ccAuthReply>
      <c:afsReply>
        <c:reasonCode>100</c:reasonCode>
        <c:afsResult>1</c:afsResult>
        <c:hostSeverity>1</c:hostSeverity>
        <c:consumerLocalTime>06:08:20</c:consumerLocalTime>
        <c:afsFactorCode>T^U</c:afsFactorCode>
        <c:addressInfoCode>UNV-ADDR</c:addressInfoCode>
        <c:internetInfoCode>FREE-EM</c:internetInfoCode>
        <c:suspiciousInfoCode>RISK-TB</c:suspiciousInfoCode>
        <c:scoreModelUsed>default</c:scoreModelUsed>
        <c:binCountry>US</c:binCountry>
        <c:cardScheme>VISA CREDIT</c:cardScheme>
        <c:cardIssuer>JPMORGAN CHASE BANK, N.A.</c:cardIssuer>
      </c:afsReply>
      <c:paySubscriptionCreateReply>
        <c:reasonCode>100</c:reasonCode>
        <c:subscriptionID>013679******1111</c:subscriptionID>
      </c:paySubscriptionCreateReply>
      <c:decisionReply>
        <c:activeProfileReply/>
      </c:decisionReply>
    </c:replyMessage>
  </soap:Body>
</soap:Envelope>


<?xml version="1.0" encoding="UTF-8"?>
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">
  <s:Header>
    <wsse:Security xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" s:mustUnderstand="1">
      <wsse:UsernameToken>
        <wsse:Username>**********</wsse:Username>
        <wsse:Password Type="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-username-token-profile-1.0#PasswordText">****</wsse:Password>
      </wsse:UsernameToken>
    </wsse:Security>
  </s:Header>
  <s:Body xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <requestMessage xmlns="urn:schemas-cybersource-com:transaction-data-1.109">
      <merchantID>squaretrad</merchantID>
      <merchantReferenceCode>c601d466-4b47-4eba-b24d-ae1cdbd8a063</merchantReferenceCode>
      <clientLibrary>Kill Bill</clientLibrary>
      <clientLibraryVersion>5.0.1</clientLibraryVersion>
      <clientEnvironment>java</clientEnvironment>
      <purchaseTotals>
        <currency>USD</currency>
        <grandTotalAmount>7.99</grandTotalAmount>
      </purchaseTotals>
      <recurringSubscriptionInfo>
        <subscriptionID>4826749006876015001014</subscriptionID>
        <approvalRequired>false</approvalRequired>
      </recurringSubscriptionInfo>
      <ccAuthService run="true"></ccAuthService>
      <ccCaptureService run="true"/>
      <businessRules></businessRules>
    </requestMessage>
  </s:Body>
</s:Envelope>
```

@SquareMike Could you also share the content of the `cybersource_*` tables?

Looking at the [tokenization tests](https://github.com/activemerchant/active_merchant/blob/master/test/unit/gateways/cyber_source_test.rb#L501-L507), they expect to have `requestID == subscriptionID`.

```
<?xml version="1.0" encoding="utf-8"?>
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
  <soap:Header>
    <wsse:Security xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd">
      <wsu:Timestamp xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" wsu:Id="Timestamp-8747786">
        <wsu:Created>2008-10-14T20:36:38.467Z</wsu:Created>
      </wsu:Timestamp>
    </wsse:Security>
  </soap:Header>
  <soap:Body>
    <c:replyMessage xmlns:c="urn:schemas-cybersource-com:transaction-data-1.32">
      <c:merchantReferenceCode>949c7098db10a846595ade653f7d259e</c:merchantReferenceCode>
      <c:requestID>2240165983980008402433</c:requestID>
      <c:decision>ACCEPT</c:decision>
      <c:reasonCode>100</c:reasonCode>
      <c:requestToken>AhjzbwSP5cIxVhZHObgEUAU2LoPM+TpAfJAwQyXRR8hAdjiAmAAA6QCH</c:requestToken>
      <c:paySubscriptionCreateReply>
        <c:reasonCode>100</c:reasonCode>
        <c:subscriptionID>2240165983980008402433</c:subscriptionID>
      </c:paySubscriptionCreateReply>
    </c:replyMessage>
  </soap:Body>
</soap:Envelope>
```

In your environment however, I see extra information returned (BIN, etc.) and the subscription is ending with `1111`, suggesting it's trying to keep the last 4. Do you have extra features enabled on your merchant account?

I believe there is a bug indeed, it's just odd we (or even upstream) never noticed it (that's why I'm wondering if your account is setup a bit differently?).

A patch like this would probably do the trick [here](https://github.com/killbill/killbill-cybersource-plugin/blob/master/lib/cybersource/ext/active_merchant/active_merchant.rb#L137) but it would be great to get to the bottom of it:

```
authorization = success ? [options[:order_id], response[:subscriptionID] || response[:requestID], response[:requestToken]].compact.join(';') : nil
```

**Comment by SquareMike** [comment]
I don't think there is any design where requestID and subscription ID would be equal, they are different from Cybersources perspective:

What is a request ID:
https://support.cybersource.com/cybskb/index?page=content&id=C151&actp=LIST

Assorted topics on subscription ID:
https://support.cybersource.com/cybskb/index?page=content&channel=CYBERSOURCE_ANSWERS&cat=C_RECURRING_BILLING_SUBSCRIPTIONS

I'm not aware of any specific account features and I will post the db contents soon.  Can we ping someone who has a test Cybersource account that can attempt to reproduce independently?

**Comment by pierre** [comment]
> I don't think there is any design where requestID and subscription ID would be equal, they are different from Cybersources perspective

I understand that they both represent different things but, at least in the sandbox, they seem to be equal. Check the [last Travis](https://travis-ci.org/killbill/killbill-cybersource-plugin/jobs/179903196) run for instance (grep for 4804621882236452204009).

> I'm not aware of any specific account features

It looks like at least the CyberSource Advanced Fraud Screen system is enabled (`afsReply` -- first time I'm seeing this element FWIW).

Would you be able to test the one-liner patch above to confirm that we have at least a workaround?

**Comment by SquareMike** [comment]
Inded: I took the Travis request, sent it to Cybersource manually and got requestID and subscriptionID the same as you said.  I then changed the creds to my test account (leaving everything else the same) and the requestID and subscriptionID were different... so I think that is pretty clear that something about my cybersource account is making them different.  The afsReply is present in mine, yours has reconciliationID, mine has cardCategory..., some other minor differences.

Is the account that Travis is using linked to an account that has production Cybersource credentials?  Maybe Cybersource doesn't bother making a real subscriptionID if the account isn't fully initialized.  I couldn't find any settings in the Cybersource website that would make my account special, although I couldn't find anything about afs either, so take that for what it's worth).

I have sent an email to Cybersource asking under which circumstances they are equal and different, just so we have some clarity.

Yes, you one-liner is the right idea, but you have to reference subscriptionID as `response['subscriptionID']`.

**Comment by pierre** [comment]
> Is the account that Travis is using linked to an account that has production Cybersource credentials?

Nope, it's just a vanilla sandbox for CI. I know that the plugin is used in production by some companies though.

> I couldn't find any settings in the Cybersource website that would make my account special, although I couldn't find anything about afs either, so take that for what it's worth).

In my experience, a lot of settings can be tweaked by the CyberSource account manager behind the scenes, so I'm not surprised you don't see anything special in the UI.

> I have sent an email to Cybersource asking under which circumstances they are equal and different, just so we have some clarity.

Great, that was my next suggestion :-)

> Yes, you one-liner is the right idea, but you have to reference subscriptionID as `response['subscriptionID']`.

Ah... Ruby... 😼  Since I cannot verify it, could you test and submit the right patch in a PR?

Also, were you able to run the integration tests against your sandbox, with your credentials? I'm just trying to find a way to have a regression test for that specific usecase (worst case, we could always hardcode your XML in a unit test in `base_plugin_spec.rb`).

**Comment by SquareMike** [comment]
If I use my CyberSource credentials with the killbill-cybersource tests then everything passes.  I think I need to write something specific that fails with my creds and then apply the "one-liner".  I do see the requestID == subscriptionID when using default creds and requestID != subscriptionID when using my creds in the test output.

**Comment by SquareMike** [comment]
I received the following response from CyberSource, trimmed and censored:

Currently the MID ‘*****’ has a backend configuration so that the Subscription ID value is ** digits instead of the default 22 digit token. This was setup back in **** in both TEST and LIVE for this account. It is also utilizing a format preserving token, so that **not important**.

I then replied asking:

Based on what you are saying, requestID is used for the subscriptionID value for CyberSource accounts that don't have a special configuration?  But from a generic perspective, it shouldn't be assumed that requestID is equal to subscriptionID because they could be different?

In which CyberSource replied:

Yes that’s a fair understanding. Just to take it one step further - the Sub ID stays the same, so while they match on the initial creation call, the RID value would be unique for the subsequent follow-on calls.

So, I believe it's incorrect to assume requestID and subscriptionID are equal even though they could be for the first call.  Even without our special configuration, as CyberSource highlights, the requestID and subscriptionID don't stay equal for very long.  I'm surprised this doesn't trip up more folks.  I will work on an improvement to the plugin that allows this and tests it.

Thank you Pierre!

**Comment by pierre** [comment]
> If I use my CyberSource credentials with the killbill-cybersource tests then everything passes.

That's odd, I would have expected token tests to fail.

Can you run the 'should be able to charge and refund' scenario for example (e.g. `bundle exec ~/.rvm/rubies/jruby-1.7.20/bin/jruby -S rspec ./spec/cybersource/remote/integration_spec.rb:364`) and verify a subscription is created, and that the subscriptionID is then used to trigger the charge?

> I'm surprised this doesn't trip up more folks.

Indeed... I'm also surprised that it's never been caught in the vanilla version of ActiveMerchant (bug present since [2012](https://github.com/activemerchant/active_merchant/commit/cb0b7a6c70994d04ff2e494b5bcce083bb9d0ca5)).

> I will work on an improvement to the plugin that allows this and tests it.

Thanks!
