### ISSUE TITLE
Handle 500 responses gracefully

### ISSUE THREAD

**Issue by pierre** [killbill/killbill-cybersource-plugin#4]
CyberSource returns 500 when the request cannot be completed (e.g. missing expiration month). ActiveMerchant will throw a `RuntimeException` in that case, which is then wrapped in a `PaymentApiException` (`org.killbill.billing.payment.api.PaymentApiException: Internal payment error : org.killbill.automaton.OperationException: {cause=null, code=7199, formattedMsg='Plugin exception Failed with 500 Internal Server Error'}`) and Kill Bill re-throw the 500 (the payment transaction status is set to `PLUGIN_FAILURE`).

With the following patch, the error is correctly parsed from the XML response (populated correctly in `gateway_error_msg`) and a 201 is returned instead (payment transaction created). Unfortunately, the transaction status is set to `UNKNOWN` because of https://github.com/killbill/killbill-plugin-framework-ruby/issues/43.

```
--- activemerchant-1.48.0/lib/active_merchant/billing/gateways/cyber_source.rb.orig	2015-06-16 05:37:33.000000000 -0700
+++ activemerchant-1.48.0/lib/active_merchant/billing/gateways/cyber_source.rb	2015-06-16 05:40:11.000000000 -0700
@@ -653,7 +653,13 @@
       # Contact CyberSource, make the SOAP request, and parse the reply into a
       # Response object
       def commit(request, options)
-        response = parse(ssl_post(test? ? self.test_url : self.live_url, build_request(request, options)))
+        request = build_request(request, options)
+        begin
+          raw_response = ssl_post(test? ? self.test_url : self.live_url, request)
+        rescue ResponseError => e
+          raw_response = e.response.body
+        end
+        response = parse(raw_response)

         success = response[:decision] == "ACCEPT"
         message = @@response_codes[('r' + response[:reasonCode]).to_sym] rescue response[:message]
```

**Comment by sbrossie** [comment]
Ah, that brings another topic. Should our JAXRS api return a 201 Created if the payment failed (does 201 mean object creation or call successful?)

**Comment by pierre** [comment]
> Should our JAXRS api return a 201 Created if the payment failed (does 201 mean object creation or call successful?)

That's the behavior today (201 even if it failed), the client has to check the transaction status.
